#:kivy 1.0.9

Interface:
    TextInput:
        id: my_textinput
        size_hint: 0.5, 0.1
        pos_hint:{"center_x":0.5, "center_y":0.6}

    Button:
        text: "Click Me"
        size_hint: 0.5, 0.1
        pos_hint:{"center_x":0.5, "center_y":0.5}
        on_press: root.buttonClicked()
    Label:
        id: my_label
        text: "Nothinf has been clicked yet"
        size_hint: 0.5, 0.2
        pos_hint:{"center_x":0.5, "center_y":0.4}
